import React from "react";
import './OrderInfoMaterialsUsed.css';

interface Props {
    text?: string;
}

export const OrderInfoMaterialsUsed = (props:Props) => {
    return (
        <div className="Order_info_materials">
            {props.text ? <h3>{props.text}</h3> : null}
            <div className="Order_info_materials_container">
                <table>
                    <thead>
                    <tr>
                        <th>Lp</th>
                        <th>Nazwa</th>
                        <th>Ilość</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Recznik</td>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Płyn</td>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Freaz</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Recznik</td>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Płyn</td>
                        <td>30</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    )
}